USE [master]
GO

/****** Object:  Database [PRSistemas]    Script Date: 21/08/2022 16:26:42 ******/
CREATE DATABASE [PRSistemas]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRSistemas', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\PRSistemas.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PRSistemas_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\PRSistemas_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PRSistemas] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRSistemas].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PRSistemas] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PRSistemas] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PRSistemas] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PRSistemas] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PRSistemas] SET ARITHABORT OFF 
GO

ALTER DATABASE [PRSistemas] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PRSistemas] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PRSistemas] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PRSistemas] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PRSistemas] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PRSistemas] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PRSistemas] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PRSistemas] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PRSistemas] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PRSistemas] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PRSistemas] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PRSistemas] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PRSistemas] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PRSistemas] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PRSistemas] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PRSistemas] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PRSistemas] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PRSistemas] SET RECOVERY FULL 
GO

ALTER DATABASE [PRSistemas] SET  MULTI_USER 
GO

ALTER DATABASE [PRSistemas] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PRSistemas] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PRSistemas] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PRSistemas] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PRSistemas] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PRSistemas] SET  READ_WRITE 
GO

